version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: conversion_nginx
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    networks:
      - conversion

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: conversion_php
    volumes:
      - ./:/var/www/html
    networks:
      - conversion

networks:
  conversion:
    name: conversion
